#ifndef XXHARDWARE_H_INCLUDED
#define XXHARDWARE_H_INCLUDED

#define RELAIS1_PORT PORTB
#define RELAIS1_PIN  PIN2_bm
#define RELAIS2_PORT PORTB
#define RELAIS2_PIN  PIN1_bm

#define RELAIS1SETUP RELAIS1_PORT.DIRSET=RELAIS1_PIN
#define RELAIS1_ON   RELAIS1_PORT.OUTCLR=RELAIS1_PIN
#define RELAIS1_OFF  RELAIS1_PORT.OUTSET=RELAIS1_PIN
#define RELAIS1_TOGGLE  RELAIS1_PORT.OUTTGL=RELAIS1_PIN

#define RELAIS2SETUP RELAIS2_PORT.DIRSET=RELAIS2_PIN
#define RELAIS2_ON   RELAIS2_PORT.OUTCLR=RELAIS2_PIN
#define RELAIS2_OFF  RELAIS2_PORT.OUTSET=RELAIS2_PIN
#define RELAIS2_TOGGLE  RELAIS2_PORT.OUTTGL=RELAIS2_PIN

#endif // XXHARDWARE_H_INCLUDED
